import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " bg-[#0B0618] text-[#FBF7F4] max-w-[1920px] mx-auto"
        }
      >
        <Navbar />
        <main className="max-w-[1000px] mx-auto px-4">{children}</main>
      </body>
    </html>
  );
}
